### ISSUE TITLE
Error on server launch ('requests' package issue)

### ISSUE THREAD

**Issue by yotamsha** [tessera-metrics/tessera#533]
I'm using  OSX 10.9.5

When I am running:
 TESSERA_CONFIG=/app_path/config.py tessera

I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/tessera", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests==2.4.3
```

I have installed requests with version 2.4.3 , but still no luck.

**Comment by aalpern** [comment]
I'm finally getting some more work on this project going - if you still remember anything about this issue, were you installing tessera with `pip install tessera`, or running from source?
